"""The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math


def count_divisors(n):
    divisors = 0
    sqrt_n = int(math.sqrt(n))
    for i in range(1, sqrt_n + 1):
        if n % i == 0:
            divisors += 2
    if sqrt_n * sqrt_n == n:
        divisors -= 1
    return divisors


def find_triangle_with_divisors(target_divisors):
    n = 1
    while True:
        triangle_number = n * (n + 1) // 2
        if n % 2 == 0:
            divisors = count_divisors(n // 2) * count_divisors(n + 1)
        else:
            divisors = count_divisors(n) * count_divisors((n + 1) // 2)

        if divisors > target_divisors:
            return triangle_number

        n += 1


print(find_triangle_with_divisors(500))


