public class Project_Euler2 {
    public static void main(String[] args) {

        // 2'nd Problem
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        // By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        int i = 0;
        int k = 1;
        int m;
        int sum = 0;
        System.out.println(i);
        for (int l = 0; l < 33; l++) {
            i = i + k;
            m = i;
            m = m - k;
            k = m;
            if (i % 2 == 0) {
                System.out.println("Sum is " + (sum = sum + i));
            }
        }
        System.out.println("Final sum is: " + sum);
    }
}
